# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :expanded

repository: jacobbf/y2ynewhaven.org
