title: 'Y2Y New Haven'

author:
  name: 'Jake Brussel Faria'

description: >
  Everything you need to know about lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Quisque ut condimentum est. Morbi eu tortor ante.
